name: event_manager_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.9.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/events.json


